config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: 'home#index'
  resources :keywords, only: [:index, :new, :create]

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:twitter]
  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    unless user
      user = User.create(
        uid: auth.uid,
        provider: auth.provider,
        email: User.get_email(auth),
        password: Devise.friendly_token[4, 30])
    end
    user
  end

  private
    def self.get_email(auth)
      email = auth.info.email
      email = "#{auth.provider}-#{auth.uid}@example.com" if email.blank?
      email
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def twitter
    @user = User.find_for_oauth(request.env['omniauth.auth'])
    if @user.persisted?
      cookies.permanent[:xxx_logined] = { value: @user.created_at }
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: 'Twitter')
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.twitter_data'] = request.env['omniauth.auth'].except('extra')
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/views/home/index.html.slim
.section.center-align
  h1 ほげほげ！w
  .row
    p.s12 ほげほげ！wほげほげ！wほげほげ！wほげほげ！wほげほげ！wほげほげ！w
  .row
    = link_to 'サインイン', user_omniauth_authorize_path(:twitter), class: 'btn-large'

.section.center-align.grey.lighten-5
  .container
    .row
      .col.m4
        .center.promo
          i.material-icons reply
          h2.promo-caption ふぁぼ・リツイートを自動化
          p.light.center
            |
              特定のキーワードでタイムライン上のツイートを自動でふぁぼ・リツイートできます。

      .col.m4
        .center.promo
          i.material-icons done
          h2.promo-caption シンプルですぐに利用できる
          p.light.center
            |
              登録に必要なのはTwitterによる認証だけなので、今すぐ利用を開始できます。

      .col.m4
        .center.promo
          i.material-icons message
          h2.promo-caption 使いやすい管理画面
          p.light.center
            |
              すっきりと見やすいマテリアルデザインの管理画面です。

.section.center-align
  .row
    h5.col.s12 登録に必要なのはツイッターのアカウントのみ、今すぐ使ってみる
  .row
    = link_to 'サインイン', user_omniauth_authorize_path(:twitter), class: 'btn-large'

app/views/keywords/index.html.slim
.container
  br
  br

  table.striped.centered
    thead
      tr
        th キーワード
        th ふぁぼ
        th リツイート

    tbody
      tr
        td ほげほげ
        td
        td
      tr
        td ふがふが
        td
        td
      tr
        td ぴよぴよ
        td
        td

app/views/keywords/new.html.slim
.container
  br
  br
  .row
    form.col.s12
      .row
        .input-field.col.s12
           <input placeholder="キーワードを入力してください" id="first_name" type="text" class="validate">
           <label for="first_name">キーワード</label>
      .row
        .input-field.col.s6
          <input type="checkbox" class="filled-in" id="favo" />
          <label for="favo">ふぁぼ</label>
        .input-field.col.s6
          <input type="checkbox" class="filled-in" id="retweet" />
          <label for="retweet">リツイート</label>
      .row
        .input-field.col.s12
          <input type="submit" class="btn" value="送信" />

app/views/layouts/_header.html.slim
header
nav.pink.lighten-3
  .container
    = link_to 'ふぁぼりっと', root_url, class: 'brand-logo'
    
    ul.right.hide-on-med-and-down
      li
        = link_to '管理画面', new_keyword_path, class: ''
      li 
        - if user_signed_in?
          = link_to 'サインアウト', destroy_user_session_path, method: :delete
        - else
          = link_to 'サインイン', user_omniauth_authorize_path(:twitter)
          
  <a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>

app/views/layouts/_management_screen_header.html.slim
header
nav.pink.lighten-3
  ul#slide-out.side-nav.fixed
    li
      = image_tag("logo.jpg", size: '100x100')
    li
      = link_to 'ふぁぼ＆リツイート', new_keyword_path, class: ''
    li
      = link_to '一覧', keywords_path, class: ''
    li
      - if user_signed_in?
        = link_to 'サインアウト', destroy_user_session_path, method: :delete
      - else
        = link_to 'サインイン', user_omniauth_authorize_path(:twitter)

  .container
    ul.right.hide-on-med-and-down
      li ふぁぼ＆リツイート

  <a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>

app/views/layouts/application.html.slim
DOCTYPE
html
  head
    title ふぁぼりっと
    meta name='viewport' content='width=device-width, initial-scale=1.0'
    link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = stylesheet_link_tag controller.controller_name, media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body

    - if controller.controller_name == 'keywords'
      = render partial: 'layouts/management_screen_header'
    - else
      = render partial: 'layouts/header'

    p.notice = notice
    p.alert = alert

    / .container

    == yield